ifeq ($(strip $(BLUETOOTH_USE_BPLUS)),true)
include $(CLEAR_VARS)
LOCAL_MODULE := Bluetooth
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)
LOCAL_SRC_FILES := $(LOCAL_MODULE).bplus$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
endif
include $(call all-makefiles-under,$(LOCAL_PATH))
